services:
  app:
    image: ghcr.io/basketikun/infinite-canvas:latest
    container_name: infinite-canvas
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped
